### PR TITLE
fix: Support `schedule.rate` defined as an array

### LINKED ISSUE #20: TypeError: schedule.rate.match is not a function
Hi, this error started today on my nightly deploy task:

```
Serverless: Converting local crontabs to UTC crontabs...
 
 Type Error ----------------------------------------------
 
  TypeError: schedule.rate.match is not a function
      at ServerlessLocalCrontabs.convertCrontabs (/root/project/build/node_modules/serverless-local-schedule/index.js:73:37)
      at PluginManager.invoke (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:580:20)
      at async PluginManager.spawn (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:602:5)
      at async Object.before:deploy:deploy [as hook] (/root/project/build/node_modules/serverless/lib/plugins/deploy.js:61:11)
      at async PluginManager.invoke (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:580:9)
      at async PluginManager.run (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:640:7)
      at async Serverless.run (/root/project/build/node_modules/serverless/lib/Serverless.js:457:5)
      at async /root/project/build/node_modules/serverless/scripts/serverless.js:803:9
```

I believe it relates to this bit of configuration in serverless.yml:

```
  subscriptions-f:
    environment: ${file(.env.json)}
    handler: dist/subscriptions-f-handler.handler
    timeout: 900
    events:
      - sns:
          arn: ${file(.env.json):USER_CHAIN_TOPIC}
      - schedule:
          rate: cron(0 * * * ? *)
          timezone: Europe/London
          input:
            topic: 'main'
```

I was able to deploy the same code to UAT and to Production 2 days ago - this issue started on nightly provisioning only.

I don't know if it matters, I have been using serverless-local-schedule for about 1 year but with frameworkVersion < 2.
Now I'm using frameworkVersion: "2"

Any idea? Thank you!

### PR DESCRIPTION
**Pull request by ramblingenzyme**
Fixes https://github.com/serverless/serverless-local-schedule/issues/20
* This code works correctly when multiple crontabs are configured in one schedule
* This code will also fallback correctly if schedule.rate is still a string and not an array.

* When serverless added the ability to configure multiple rates in a schedule, they also removed the ability to set names when configuring multiple schedules. https://github.com/serverless/serverless/issues/9867 This was causing my local testing to fail.
   * This means we shouldn't add a numbered name to schedules
   * I've also removed the name in the test schedule

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -97,7 +106,6 @@ function convertCrontabs() {
           ...newCrontabs.map((crontab, i) => ({
             schedule: Object.assign({}, schedule, {
               rate: `cron(${crontab})`,
-              name: schedule.name && `${schedule.name}-${i}`
```
Comment (pgrzesik) [inline index.js:100]: Should we always remove that naming here? If I understand, it's not supported when there are multiple rates specified

Comment (ramblingenzyme) [reply index.js:100]: Yup, that's correct, so if `newCrontabs` has more than one entry or if `schedule.rate` has more than one entry, the name property is invalid in current Serverless versions.

I can make it so that the naming still is applied when `schedule.rate` is a string to maintain the old behavior for older serverless versions.

Comment (pgrzesik) [reply index.js:100]: I think it would make sense to keep the behavior consistent for older versions

Comment (ramblingenzyme) [reply index.js:100]: @pgrzesik I've updated this now.

File: index.js [hunk 2]
```diff
@@ -71,20 +71,31 @@ function convertCrontabs() {
         event.schedule.hasOwnProperty("timezone")
       ) {
         const schedule = event.schedule;
-        const match = schedule.rate.match(/^cron\((.*)\)$/);
-        if (!match)
+        const isNewServerlessVersion = Array.isArray(schedule.rate);
```
Comment (pgrzesik) [inline index.js]: why is that property called `isNewServerlessVersion` - it's quite ambiguous meaning - could we make this more clear?

**Review by pgrzesik — CHANGES_REQUESTED** [review]
I have one comment about the naming of used variable as I think it's quite ambiguous - could we improve it?

File: index.js (hunk 2 above)
Comment (ramblingenzyme) [reply index.js]: Do you have any suggestions? Would a comment explaining it be enough?
It's being used to switch between the current behaviour and what needs to change for newer Serverless versions.
Is there a better way to encapsulate that?

Comment (pgrzesik) [reply index.js]: I would name it like `hasRateDefinedAsArray` and add an explanation with a comment above it - what do you think?

Comment (ramblingenzyme) [reply index.js]: I've had a stab at it, should I change it again?

**Review by pgrzesik — APPROVED** [review]
Looks good, thanks @ramblingenzyme 🙇
